Repository gcu-LastDance/GachonOJ-Backend, pull requests merged in 2024-05, with the labels that each got.

#75 [feat] 비밀번호 찾기 api 구현 로그인 errorcode 구분
  Member-Service/src/main/java/com/gachonoj/memberservice/common/codes/ErrorCode.java
  Member-Service/src/main/java/com/gachonoj/memberservice/controller/MemberController.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
Labels: feat ✨, 민혁 🐥

#77 [fix] 게시판 서비스 응답 수정 및 문제 내비바 조회 api 수정
  Board-Service/src/main/java/com/gachonoj/boardservice/domain/dto/response/InquiryDetailAdminResponseDto.java
  Board-Service/src/main/java/com/gachonoj/boardservice/domain/dto/response/InquiryDetailResponseDto.java
  Board-Service/src/main/java/com/gachonoj/boardservice/domain/dto/response/NoticeDetailResponseDto.java
Labels: fix 💥, 민혁 🐥

#80 [feat] 문제 상태 추가 및 코드 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/constant/ProblemStatus.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ProblemRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
Labels: feat ✨, 민혁 🐥

#82 [feat] 문제 분류 추가
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/constant/ProblemClass.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/constant/TestcaseStatus.java
Labels: feat ✨, 민혁 🐥

#84 [feat] #69 feat 북마크 취소 시험 문제 수정 문제 수정 기능 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/request/ProblemRequestDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemDetailAdminResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/TestcaseResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/BookmarkRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ProblemRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
Labels: feat ✨, 기헌

#87 [feat] 회원 정보 수정 api 기존 이미지 삭제 구현
  Member-Service/src/main/java/com/gachonoj/memberservice/domain/dto/response/MemberInfoResponseDto.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
Labels: feat ✨, 민혁 🐥

#89 [fix] 선호 언어 변경 api 수정 문제 상세조회 api 수정
  Member-Service/src/main/java/com/gachonoj/memberservice/domain/dto/request/MemberLangRequestDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
Labels: fix 💥, 민혁 🐥

#92 [feat] 코드 제출 고도화
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/ProblemServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#94 [feat] 문제 채점 저장 로직 구현
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/entity/Submission.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#95 [feat] ai 피드백 api 구현
  AI-Service/src/main/java/com/gachonoj/aiservice/AiServiceApplication.java
  AI-Service/src/main/java/com/gachonoj/aiservice/config/OpenAiConfig.java
  AI-Service/src/main/java/com/gachonoj/aiservice/controller/AiController.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/request/ChatGPTRequest.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/request/FeedbackRequestDto.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/response/AiFeedbackResponseDto.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/response/ChatGPTResponse.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/response/Message.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/entity/Feedback.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/client/ProblemServiceFeignClient.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/client/SubmissionServiceFeignClient.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/controller/AiFeignController.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/dto/response/SubmissionCodeInfoResponseDto.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/service/AiFeignService.java
  AI-Service/src/main/java/com/gachonoj/aiservice/service/AiService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/entity/Submission.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/SubmissionCodeInfoResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
Labels: feat ✨, 민혁 🐥

#101 [fix] 관리자 문제 목록 조회 API 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ProblemRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
Labels: fix 💥, 민혁 🐥

#106 [feat] 교수 관리자 대시보드 api 구현
  APIGateway/src/main/java/com/gachonoj/apigateway/config/SecurityConfig.java
  Member-Service/src/main/java/com/gachonoj/memberservice/controller/MemberController.java
  Member-Service/src/main/java/com/gachonoj/memberservice/domain/dto/response/MemberLangCountResponseDto.java
  Member-Service/src/main/java/com/gachonoj/memberservice/repository/MemberRepository.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamCardInfoResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemCardResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/dto/response/CorrectRateResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/dto/response/SubmissionResultCountResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ExamRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/response/TodaySubmissionCountResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/CorrectRateResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/SubmissionResultCountResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#108 [fix] 문제 조회 지난시험대회 응시자 추가 api 수정
  Member-Service/src/main/java/com/gachonoj/memberservice/controller/MemberController.java
  Member-Service/src/main/java/com/gachonoj/memberservice/repository/MemberRepository.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/response/SubmissionResultResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: fix 💥, 민혁 🐥

#111 [fix] Bean 순환 참조 문제 해결
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/ExecuteService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: fix 💥, 민혁 🐥

#112 [fix] 목록조회 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemListResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/BookmarkRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
Labels: feat ✨, 민혁 🐥

#114 [fix] 코드 실행 API 에러 해결
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/ExecuteService.java
Labels: fix 💥, 민혁 🐥

#117 [fix] 시험 저장 api 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 민혁 🐥

#118 Feature/#91 feat 시험 결과 확인 조회 시험 결과 목록 조회 api 구현
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/controller/MemberFeignController.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/dto/response/ProblemMemberInfoResponseDto.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/service/MemberFeignService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultDetailsResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultListDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/QuestionResultDetailsResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/MemberServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/dto/response/ProblemMemberInfoResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/dto/response/SubmissionDetailDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/dto/response/SubmissionExamResultInfoResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/SubmissionDetailDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/SubmissionExamResultInfoResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 기헌

#120 [feat] 관리페이지 프로필 조회 ai 사용 토큰 갯수 조회 응시하기 api
  AI-Service/src/main/java/com/gachonoj/aiservice/AiServiceApplication.java
  AI-Service/src/main/java/com/gachonoj/aiservice/controller/AiController.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/response/TokenUsageResponseDto.java
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/entity/Feedback.java
  AI-Service/src/main/java/com/gachonoj/aiservice/repository/FeedbackRepository.java
  AI-Service/src/main/java/com/gachonoj/aiservice/service/AiService.java
  Member-Service/src/main/java/com/gachonoj/memberservice/repository/MemberRepository.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/common/codes/ErrorCode.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamEnterResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/response/MySubmissionResultResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/MemberServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/ProblemServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, fix 💥, 민혁 🐥

#121 [feat] #119 제출 목록 조회 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/response/SubmissionRecordResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 기헌

#125 [fix] 시험 삭제 api 수정 및 에러사항 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/entity/Question.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/entity/Test.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ExamRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/constant/Status.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/response/SubmissionRecordResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/entity/Submission.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#127 [fix] #126 시험 문제 조회 LocalDateTime 형식 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#129 [fix] #128 대기 화면 LocalDateTime 형식 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#132 Feature/#131 feat 시험 점수 조회 api 구현 좋아요 기능 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultListDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultPageDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/entity/Love.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/LoveRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/LoveService.java
Labels: feat ✨, 기헌

#134 [feat] 시험 제출 api 구현
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/dto/request/ExamSubmitRequestDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#136 [fix] 제출 서비스 레포지토리 에러해결
  Submission-Service/src/main/java/com/gachonoj/submissionservice/domain/entity/Love.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/LoveRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/LoveService.java
Labels: fix 💥, 민혁 🐥

#138 [fix] #133 시험 수정 기능 미완. PutMapping 쪽 보완 부탁..
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/entity/Test.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: feat ✨, fix 💥, 기헌

#140 Fix/#139 fix 시험 api 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ProblemRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#141 [feat] #137 문제 목록 API 응답 추가
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemListResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
Labels: feat ✨, 민혁 🐥

#143 [fix] #142 시험 수정 api 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultListDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#146 [fix] #145 memberId 처리 수정 완료
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#147 [feat] 관리자 대시보드 최근문의사항, 시험 채점 구현, ai 피드백 응답추가
  AI-Service/src/main/java/com/gachonoj/aiservice/domain/dto/response/AiFeedbackResponseDto.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/client/MemberServiceFeignClient.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/client/ProblemServiceFeignClient.java
  AI-Service/src/main/java/com/gachonoj/aiservice/service/AiService.java
  Board-Service/src/main/java/com/gachonoj/boardservice/controller/BoardController.java
  Board-Service/src/main/java/com/gachonoj/boardservice/domain/dto/response/InquiryAdminListResponseDto.java
  Board-Service/src/main/java/com/gachonoj/boardservice/repository/InquiryRepository.java
  Board-Service/src/main/java/com/gachonoj/boardservice/service/BoardService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/ProblemServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 민혁 🐥

#150 Feature/#148 feat 시험 결과 목록 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultPageDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/ProblemServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/dto/response/SubmissionCodeInfoResponseDto.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: feat ✨, 기헌

#152 [fix] #148 시험 결과 상세 조회 구현 완료
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
Labels: fix 💥, 기헌

#154 [feat] devops 모니터링 기능 구현
  AI-Service/build.gradle
  APIGateway/build.gradle
  APIGateway/src/main/java/com/gachonoj/apigateway/config/SecurityConfig.java
  Board-Service/build.gradle
  EurekaServer/build.gradle
  Member-Service/build.gradle
  Problem-Service/build.gradle
  Submission-Service/build.gradle
Labels: feat ✨, 민혁 🐥

#157 [feat] 시험 점수 확인, 학생 시험 목록 조회 api 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamCardInfoResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/TestOverviewResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ExamRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: feat ✨, 기헌

#160 Revert 159 dev
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: feat ✨, 기헌

#163 [feat] 삭제시 외래키로 사용하고있던 다른 db 삭제
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/controller/AiFeignController.java
  AI-Service/src/main/java/com/gachonoj/aiservice/feign/service/AiFeignService.java
  AI-Service/src/main/java/com/gachonoj/aiservice/repository/FeedbackRepository.java
  Board-Service/src/main/java/com/gachonoj/boardservice/feign/controller/BoardFeignController.java
  Board-Service/src/main/java/com/gachonoj/boardservice/feign/service/BoardFeignService.java
  Board-Service/src/main/java/com/gachonoj/boardservice/repository/InquiryRepository.java
  Board-Service/src/main/java/com/gachonoj/boardservice/repository/NoticeRepository.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/client/AiServiceFeignClient.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/client/BoardServiceFeignClient.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/client/ProblemServiceFeignClient.java
  Member-Service/src/main/java/com/gachonoj/memberservice/feign/client/SubmissionServiceFeignClient.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/AiServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/SubmissionServiceFeignClient.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/BookmarkRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ExamRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/TestRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/controller/SubmissionFeignController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/LoveRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/repository/SubmissionRepository.java
Labels: feat ✨, 민혁 🐥

#166 [fix] Feign Method 오류 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/client/AiServiceFeignClient.java
Labels: fix 💥, 민혁 🐥

#168 [fix] #164 시험 결과 목록 조회하는 부분 수정 완료하였습니다.
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: fix 💥, 기헌

#170 [fix] 시험문제 답안 제출 문제 답안 제출 오류수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/controller/SubmissionController.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/ExecuteService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: fix 💥, 민혁 🐥

#172 [fix] 랭킹 API 푼 문제수, 도전중인 문제 수 수정
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/controller/ProblemFeignController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/feign/service/ProblemFeignService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/ProblemRepository.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/client/ProblemServiceFeignClient.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/feign/service/SubmissionFeignService.java
Labels: fix 💥, 민혁 🐥

#173 [feat] 문제 목록 조회 검색, 오름차순 구현
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
Labels: feat ✨, 민혁 🐥

#178 [fix]시험 문제 삭제 API 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/repository/QuestionRepository.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 민혁 🐥

#179 [fix] 시험 목록 조회 API 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ExamResultPageDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 민혁 🐥

#181 [fix] 시험 결과 목록 조회 API 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 민혁 🐥
