Repository gcu-LastDance/GachonOJ-Backend, pull requests merged in 2024-06, with the labels that each got.

#183 [fix] #182 제출 인원 오류 수정 완료
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#185 [fix] #184 시험 문제 등록
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#186 [fix] #184 시험 문제 등록 수정
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/entity/Question.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ExamService.java
Labels: fix 💥, 기헌

#187 [docs] readme 파일 작성
  README.md
Labels: docs 📄, 민혁 🐥

#189 [refactor] 소스 코드 리팩토링
  AI-Service/src/main/java/com/gachonoj/aiservice/controller/AiController.java
  AI-Service/src/main/java/com/gachonoj/aiservice/service/AiService.java
  Board-Service/src/main/java/com/gachonoj/boardservice/domain/dto/response/ReplyResponseDto.java
  Board-Service/src/main/java/com/gachonoj/boardservice/service/BoardService.java
  Member-Service/src/main/java/com/gachonoj/memberservice/domain/dto/response/MemberListResponseDto.java
  Member-Service/src/main/java/com/gachonoj/memberservice/service/MemberService.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/controller/ProblemController.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/request/CandidateListRequestDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/request/QuestionRequestDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/BookmarkProblemResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/PastContestResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ProblemDetailResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/QuestionResultDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/ScheduledContestResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/SolvedProblemResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/domain/dto/response/WrongProblemResponseDto.java
  Problem-Service/src/main/java/com/gachonoj/problemservice/service/ProblemService.java
  Submission-Service/src/main/java/com/gachonoj/submissionservice/service/SubmissionService.java
Labels: refactor 🧹, 민혁 🐥

#191 [feat] Docker compose 파일 추가
  docker-compose-database.yml
  docker-compose-monitoring.yml
  docker-compose-service.yml
Labels: feat ✨, 민혁 🐥
